services:
  diva_postgre_sql:
    container_name: diva_postgre_sql
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${LOCAL_POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${LOCAL_POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgre_sql:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.18.0.30

  diva_pgadmin:
    user: root
    container_name: diva_pgadmin
    image: dpage/pgadmin4:8.14.0
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin/

    networks:
      app_net:
        ipv4_address: 172.18.0.31

  diva_rabbitmq:
    container_name: diva_rabbitmq
    image: rabbitmq:management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq/rabbitmq_data:/var/lib/rabbitmq
      - ./volumes/rabbitmq/rabbitmq_log:/var/log/rabbitmq
    networks:
      app_net:
        ipv4_address: 172.18.0.32

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
