import os
from dotenv import load_dotenv


load_dotenv(override=True)


class Config:
    NAS_IP = os.getenv("NAS_IP")
    NAS_PORT = os.getenv("NAS_PORT")
    NAS_USERNAME = os.getenv("NAS_USERNAME")
    NAS_PASSWORD = os.getenv("NAS_PASSWORD")
    PGADMIN_EMAIL = os.getenv("PGADMIN_EMAIL")
    PGADMIN_PASSWORD = os.getenv("PGADMIN_PASSWORD")
    LOCAL_POSTGRESQL_USER = os.getenv("LOCAL_POSTGRESQL_USER")
    LOCAL_POSTGRESQL_PASSWORD = os.getenv("LOCAL_POSTGRESQL_PASSWORD")
    LOCAL_POSTGRESQL_DATABASE = os.getenv("LOCAL_POSTGRESQL_DATABASE")
    LOCAL_POSTGRESQL_HOST = os.getenv("LOCAL_POSTGRESQL_HOST")
    MIDDLEWARE_SECRET_KEY = os.getenv("MIDDLEWARE_SECRET_KEY")
    RABBITMQ_DEFAULT_USER = os.getenv("RABBITMQ_DEFAULT_USER")
    RABBITMQ_DEFAULT_PASS = os.getenv("RABBITMQ_DEFAULT_PASS")
    RABBITMQ_DEFAULT_HOST = os.getenv("RABBITMQ_DEFAULT_HOST")
    PGSQL_CONNECTION = f"postgresql+psycopg2://{LOCAL_POSTGRESQL_USER}:{LOCAL_POSTGRESQL_PASSWORD}@{LOCAL_POSTGRESQL_HOST}/{LOCAL_POSTGRESQL_DATABASE}"
    PGSQL_BACKEND = f"db+postgresql://{LOCAL_POSTGRESQL_USER}:{LOCAL_POSTGRESQL_PASSWORD}@{LOCAL_POSTGRESQL_HOST}:5432/{LOCAL_POSTGRESQL_DATABASE}"
    BROKER_URL = f"amqp://{RABBITMQ_DEFAULT_USER}:{RABBITMQ_DEFAULT_PASS}@{RABBITMQ_DEFAULT_HOST}"
